# Generated by Django 3.2.4 on 2021-07-10 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formapp4', '0003_remove_task_priority'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='task',
            table='task',
        ),
    ]
