# Generated by Django 3.2.4 on 2021-07-10 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formapp4', '0004_alter_task_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-text']},
        ),
    ]
